# Generated by Django 5.2.10 on 2026-02-02 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('sc_no', models.CharField(max_length=16)),
                ('phase', models.CharField(choices=[('Single', 'Single'), ('Three', 'Three')], max_length=20)),
                ('feasibility_kw', models.FloatField()),
                ('aadhar_no', models.CharField(max_length=12)),
                ('pan_card', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('roof_type', models.CharField(max_length=100)),
                ('structure_type', models.CharField(max_length=100)),
                ('structure_height', models.FloatField()),
                ('gps_coordinates', models.CharField(max_length=100)),
                ('agreed_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registration_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_serial_photo', models.ImageField(upload_to='installations/panels/')),
                ('inverter_make', models.CharField(max_length=100)),
                ('inverter_serial_photo', models.ImageField(upload_to='installations/inverters/')),
                ('ac_cable_length', models.FloatField()),
                ('dc_cable_length', models.FloatField()),
                ('app_status', models.BooleanField(default=False)),
                ('site_photos_with_customer', models.ImageField(upload_to='installations/site/')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solar_management.customersurvey')),
            ],
        ),
    ]
