# Generated by Django 5.2.10 on 2026-02-02 08:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installation',
            old_name='app_status',
            new_name='app_installation_status',
        ),
        migrations.RemoveField(
            model_name='installation',
            name='ac_cable_length',
        ),
        migrations.RemoveField(
            model_name='installation',
            name='dc_cable_length',
        ),
        migrations.AddField(
            model_name='installation',
            name='ac_cable_used',
            field=models.FloatField(default=0, help_text='in Meters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installation',
            name='dc_cable_used',
            field=models.FloatField(default=0, help_text='in Meters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installation',
            name='la_cable_used',
            field=models.FloatField(default=0, help_text='in Meters'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='installation',
            name='survey',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installation', to='solar_management.customersurvey'),
        ),
    ]
