# Generated by Django 5.2.10 on 2026-02-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0002_rename_app_status_installation_app_installation_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_bank', models.CharField(max_length=100)),
                ('parent_bank_ac_no', models.CharField(max_length=20)),
                ('loan_applied_bank', models.CharField(max_length=100)),
                ('loan_applied_ifsc', models.CharField(max_length=11)),
                ('loan_applied_ac_no', models.CharField(max_length=20)),
                ('loan_pending_status', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Both', 'Both'), ('Pending', 'Pending')], max_length=20)),
                ('first_loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('first_loan_utr', models.CharField(blank=True, max_length=50)),
                ('first_loan_date', models.DateField(blank=True, null=True)),
                ('second_loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('second_loan_utr', models.CharField(blank=True, max_length=50)),
                ('second_loan_date', models.DateField(blank=True, null=True)),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='solar_management.customersurvey')),
            ],
        ),
    ]
