# Generated by Django 5.2.10 on 2026-02-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='mefma_status',
            field=models.BooleanField(default=False, help_text='Is MEFMA approved?'),
        ),
        migrations.AddField(
            model_name='installation',
            name='customer_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='pipes_used',
            field=models.FloatField(default=0.0, help_text='in Meters'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='la_cable_used',
            field=models.FloatField(default=0.0, help_text='in Meters'),
        ),
    ]
