# Generated by Django 5.2.10 on 2026-02-02 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0005_customersurvey_mefma_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='aadhar_linked_phone',
            field=models.CharField(default='0000000000', max_length=10),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='fe_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='roof_photo',
            field=models.ImageField(blank=True, null=True, upload_to='surveys/roofs/'),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='rp_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='rp_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='installer_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='inverter_acdb_photo',
            field=models.ImageField(blank=True, null=True, upload_to='installations/acdb/'),
        ),
        migrations.AddField(
            model_name='installation',
            name='inverter_phase',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='installation',
            name='leftover_materials',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='installation',
            name='warranty_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='roof_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Plastic shed', 'Plastic shed'), ('Cement shed', 'Cement shed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='structure_height',
            field=models.FloatField(help_text='in Feet'),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='structure_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Vertical', 'Vertical'), ('Horizontal', 'Horizontal')], max_length=100),
        ),
    ]
