# Generated by Django 5.2.10 on 2026-02-04 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0006_customersurvey_aadhar_linked_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='workflow_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
