# Generated by Django 5.0.1 on 2026-02-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0008_enquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='area',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='connection_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='division',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='pms_registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='reference_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
