# Generated by Django 5.0.1 on 2026-02-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0009_customersurvey_advance_paid_customersurvey_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='ac_voltage',
            field=models.FloatField(default=0.0, help_text='in Volts'),
        ),
        migrations.AddField(
            model_name='installation',
            name='dc_voltage',
            field=models.FloatField(default=0.0, help_text='in Volts'),
        ),
        migrations.AddField(
            model_name='installation',
            name='earthing_resistance',
            field=models.FloatField(default=0.0, help_text='in Ohms'),
        ),
    ]
