# Generated by Django 5.0.1 on 2026-02-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0010_installation_ac_voltage_installation_dc_voltage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Field Engineer', 'Field Engineer'), ('Installer', 'Installer'), ('Office', 'Office'), ('Admin', 'Admin')], max_length=20),
        ),
    ]
