# Generated by Django 5.0.1 on 2026-02-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0011_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersurvey',
            name='aadhar_linked_phone',
            field=models.CharField(default='0000000000', help_text='10 Digits', max_length=10),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='aadhar_no',
            field=models.CharField(help_text='12 Digits', max_length=12),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='area',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='connection_type',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('Commercial', 'Commercial'), ('GHS', 'GHS')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='feasibility_kw',
            field=models.FloatField(help_text='Applied Solar Load (KW)'),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='pan_card',
            field=models.CharField(help_text='10 Digits', max_length=10),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='phase',
            field=models.CharField(choices=[('Single Phase', 'Single Phase'), ('Three Phase', 'Three Phase')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='phone_number',
            field=models.CharField(help_text='10 Digits', max_length=10),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='roof_photo',
            field=models.ImageField(blank=True, help_text='Mandatory if critical site', null=True, upload_to='surveys/roofs/'),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='sc_no',
            field=models.CharField(help_text='16 Digits', max_length=16),
        ),
    ]
