# Generated by Django 5.2.10 on 2026-02-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0012_alter_customersurvey_aadhar_linked_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='discom_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Applied', 'Applied'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='net_metering_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Applied', 'Applied'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='office_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='subsidy_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Applied', 'Applied'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
