# Generated by Django 5.2.10 on 2026-02-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0013_customersurvey_discom_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersurvey',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='feasibility_kw',
            field=models.FloatField(help_text='Maximum KW (Applied Solar Load)'),
        ),
    ]
