# Generated by Django 5.2.10 on 2026-02-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0015_customersurvey_installation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='manager_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Field Engineer', 'Field Engineer'), ('Installer', 'Installer'), ('Office', 'Office'), ('Admin', 'Admin'), ('Loan', 'Loan')], max_length=20),
        ),
    ]
