# Generated by Django 5.2.10 on 2026-02-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0016_bankdetails_manager_number_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='contracted_load',
            field=models.FloatField(default=0.0, help_text='Contracted Load (KW)'),
        ),
    ]
