# Generated by Django 5.2.10 on 2026-02-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0017_customersurvey_contracted_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='customer_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, help_text='Rate the experience (1-5)'),
        ),
    ]
