# Generated by Django 5.2.10 on 2026-02-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0018_installation_customer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersurvey',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
