# Generated by Django 5.2.10 on 2026-03-01 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0019_alter_customersurvey_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='aadhar_photo',
            field=models.ImageField(blank=True, help_text='Photo of Aadhar Card', null=True, upload_to='surveys/documents/'),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='current_bill_photo',
            field=models.ImageField(blank=True, help_text='Photo of Current Electricity Bill', null=True, upload_to='surveys/documents/'),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='pan_card_photo',
            field=models.ImageField(blank=True, help_text='Photo of PAN Card', null=True, upload_to='surveys/documents/'),
        ),
    ]
