# Generated by Django 5.2.10 on 2026-03-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0020_add_document_photo_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersurvey',
            name='aadhar_photo',
            field=models.FileField(blank=True, help_text='Photo/Scan of Aadhar Card', null=True, upload_to='surveys/documents/'),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='current_bill_photo',
            field=models.FileField(blank=True, help_text='Photo/Scan of Current Electricity Bill', null=True, upload_to='surveys/documents/'),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='pan_card_photo',
            field=models.FileField(blank=True, help_text='Photo/Scan of PAN Card', null=True, upload_to='surveys/documents/'),
        ),
    ]
