# Generated by Django 5.2.10 on 2026-03-01 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0021_change_doc_photos_to_filefield'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='When enabled, all pages show a maintenance screen.')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
