# Generated by Django 5.2.10 on 2026-03-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0022_add_site_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='bank_account_photo',
            field=models.FileField(blank=True, help_text='Photo/Scan of Bank Account', null=True, upload_to='surveys/documents/'),
        ),
    ]
