# Generated by Django 5.2.10 on 2026-03-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0023_customersurvey_bank_account_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='parent_bank_photo',
            field=models.FileField(blank=True, help_text='Photo/Scan of Parent Bank Front Page', null=True, upload_to='surveys/documents/'),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='registration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
