# Generated by Django 5.2.10 on 2026-03-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0024_customersurvey_parent_bank_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersurvey',
            name='structure_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Vertical', 'Vertical'), ('Horizontal', 'Horizontal'), ('Fabrication', 'Fabrication')], max_length=100),
        ),
    ]
