# Generated by Django 5.2.10 on 2026-03-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0025_alter_customersurvey_structure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='measurements',
            field=models.FloatField(blank=True, help_text='Measurements (Square Feet)', null=True),
        ),
    ]
