# Generated by Django 5.2.10 on 2026-03-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0026_customersurvey_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='co_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customersurvey',
            name='co_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='mefma_status',
            field=models.BooleanField(default=False, help_text='Yes if MEFMA, No if Not'),
        ),
        migrations.AlterField(
            model_name='customersurvey',
            name='reference_name',
            field=models.CharField(blank=True, help_text='Reference Name if not MEFMA', max_length=255, null=True),
        ),
    ]
