# Generated by Django 5.2.10 on 2026-03-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0027_customersurvey_co_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aadhar_photo',
            field=models.FileField(blank=True, help_text='Photo/Scan of Aadhar Card', null=True, upload_to='users/documents/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pan_card_photo',
            field=models.FileField(blank=True, help_text='Photo/Scan of PAN Card', null=True, upload_to='users/documents/'),
        ),
    ]
