# Generated by Django 5.2.10 on 2026-03-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0028_userprofile_aadhar_photo_userprofile_pan_card_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='floors',
            field=models.PositiveIntegerField(blank=True, help_text='Number of Floors', null=True),
        ),
    ]
