# Generated by Django 5.2.10 on 2026-03-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0029_add_floors_to_customersurvey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='loan_pending_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
