# Generated by Django 5.2.10 on 2026-03-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0030_alter_bankdetails_loan_pending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersurvey',
            name='measurements',
            field=models.CharField(blank=True, help_text='Measurements (Square Feet)', max_length=255, null=True),
        ),
    ]
