# Generated by Django 5.2.10 on 2026-03-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0031_alter_customersurvey_measurements'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='application_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='worker_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
