# Generated by Django 5.2.10 on 2026-03-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0032_customersurvey_application_id_userprofile_worker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='ac_cable_black',
            field=models.FloatField(blank=True, default=0.0, help_text='AC Cable Black in Meters'),
        ),
        migrations.AddField(
            model_name='installation',
            name='ac_cable_red',
            field=models.FloatField(blank=True, default=0.0, help_text='AC Cable Red in Meters'),
        ),
        migrations.AddField(
            model_name='installation',
            name='acdb_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of ACDBs'),
        ),
        migrations.AddField(
            model_name='installation',
            name='anchor_hardener_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of Anchor Hardeners'),
        ),
        migrations.AddField(
            model_name='installation',
            name='dc_cable_red_black',
            field=models.FloatField(blank=True, default=0.0, help_text='DC Cable Red & Black in Meters'),
        ),
        migrations.AddField(
            model_name='installation',
            name='dcdb_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of DCDBs'),
        ),
        migrations.AddField(
            model_name='installation',
            name='earthing_kit_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of Earthing Kits'),
        ),
        migrations.AddField(
            model_name='installation',
            name='inverter_kw',
            field=models.FloatField(blank=True, default=0.0, help_text='Inverter capacity in kW'),
        ),
        migrations.AddField(
            model_name='installation',
            name='inverter_phase_type',
            field=models.CharField(blank=True, choices=[('Single Phase', 'Single Phase'), ('Three Phase', 'Three Phase')], default='Single Phase', help_text='Single / Three Phase', max_length=20),
        ),
        migrations.AddField(
            model_name='installation',
            name='la_cable_mtrs',
            field=models.FloatField(blank=True, default=0.0, help_text='LA Cable in Meters'),
        ),
        migrations.AddField(
            model_name='installation',
            name='long_l_bands_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of Long L Bands'),
        ),
        migrations.AddField(
            model_name='installation',
            name='mc4_connectors_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of MC4 Connectors'),
        ),
        migrations.AddField(
            model_name='installation',
            name='nail_clamps_1side_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of 1-Side Nail Clamps'),
        ),
        migrations.AddField(
            model_name='installation',
            name='nail_clamps_2side_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of 2-Side Nail Clamps'),
        ),
        migrations.AddField(
            model_name='installation',
            name='panels_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of Panels'),
        ),
        migrations.AddField(
            model_name='installation',
            name='pipes_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of Pipes'),
        ),
        migrations.AddField(
            model_name='installation',
            name='short_l_bands_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of Short L Bands'),
        ),
        migrations.AddField(
            model_name='installation',
            name='structure_kit_type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Fabrication', 'Fabrication')], default='Normal', help_text='Normal / Fabrication', max_length=20),
        ),
        migrations.AddField(
            model_name='installation',
            name='t_bands_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of T Bands'),
        ),
        migrations.AddField(
            model_name='installation',
            name='tags_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of Tags'),
        ),
        migrations.AddField(
            model_name='installation',
            name='tapes_black_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of Black Tapes'),
        ),
        migrations.AddField(
            model_name='installation',
            name='tapes_red_count',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Number of Red Tapes'),
        ),
    ]
