# Generated by Django 5.2.10 on 2026-03-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0033_installation_ac_cable_black_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='inverter_serial_number',
            field=models.CharField(blank=True, help_text='Inverter Serial Number(s)', max_length=200),
        ),
        migrations.AddField(
            model_name='installation',
            name='panel_serial_numbers',
            field=models.TextField(blank=True, help_text='Panel Serial Numbers (one per line or comma separated)'),
        ),
    ]
