# Generated by Django 5.2.10 on 2026-03-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0034_installation_inverter_serial_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Stored for admin reference only', max_length=128),
        ),
    ]
