# Generated by Django 5.2.10 on 2026-03-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0035_userprofile_plain_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersurvey',
            name='area',
            field=models.CharField(choices=[('Rajahmundry', 'Rajahmundry'), ('Kovvur', 'Kovvur'), ('Mandapeta', 'Mandapeta'), ('Nidadavole', 'Nidadavole'), ('Others', 'Others')], max_length=255),
        ),
    ]
