# Generated by Django 5.2.10 on 2026-03-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0036_alter_customersurvey_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersurvey',
            name='area',
            field=models.CharField(max_length=255),
        ),
    ]
