# Generated by Django 5.2.10 on 2026-03-14 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0037_alter_customersurvey_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='installations/site_additional/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_photos', to='solar_management.installation')),
            ],
        ),
    ]
