# Generated by Django 5.2.10 on 2026-03-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0038_installationphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='inverter_serial_photo',
            field=models.ImageField(blank=True, null=True, upload_to='installations/inverters/'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='panel_serial_photo',
            field=models.ImageField(blank=True, null=True, upload_to='installations/panels/'),
        ),
        migrations.AlterField(
            model_name='installation',
            name='site_photos_with_customer',
            field=models.ImageField(blank=True, null=True, upload_to='installations/site/'),
        ),
    ]
