# Generated by Django 5.2.10 on 2026-03-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0039_alter_installation_inverter_serial_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installation',
            name='ac_cable_used',
            field=models.FloatField(blank=True, help_text='in Meters', null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='dc_cable_used',
            field=models.FloatField(blank=True, help_text='in Meters', null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='la_cable_used',
            field=models.FloatField(blank=True, default=0.0, help_text='in Meters', null=True),
        ),
        migrations.AlterField(
            model_name='installation',
            name='pipes_used',
            field=models.FloatField(blank=True, default=0.0, help_text='in Meters', null=True),
        ),
    ]
