# Generated by Django 5.2.10 on 2026-03-14 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0040_alter_installation_ac_cable_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationphoto',
            name='photo_type',
            field=models.CharField(choices=[('inverter_serial', 'Inverter Serial'), ('inverter_acdb', 'Inverter ACDB'), ('panel_serial', 'Panel Serial'), ('site_with_customer', 'Site with Customer'), ('additional', 'Additional Site Photos')], default='additional', max_length=50),
        ),
        migrations.CreateModel(
            name='ProfileMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='profiles/media/')),
                ('media_type', models.CharField(choices=[('aadhar', 'Aadhar Card'), ('pan_card', 'PAN Card')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='solar_management.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='surveys/media/')),
                ('media_type', models.CharField(choices=[('roof', 'Roof Photos'), ('pan_card', 'PAN Card'), ('aadhar', 'Aadhar Card'), ('current_bill', 'Current Bill'), ('bank_account', 'Bank Account'), ('parent_bank', 'Parent Bank')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='solar_management.customersurvey')),
            ],
        ),
    ]
