# Generated by Django 5.2.10 on 2026-03-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0041_installationphoto_photo_type_profilemedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installation',
            name='ac_cable_black_used',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='ac_cable_red_used',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='acdb_count_used',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='anchor_hardener_count_used',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='dc_cable_red_black_used',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='dcdb_count_used',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='earthing_kit_count_used',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='inverter_kw_used',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='inverter_phase_type_used',
            field=models.CharField(blank=True, choices=[('Single Phase', 'Single Phase'), ('Three Phase', 'Three Phase')], default='Single Phase', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='la_cable_mtrs_used',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='long_l_bands_count_used',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='mc4_connectors_count_used',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='nail_clamps_1side_count_used',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='nail_clamps_2side_count_used',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='panels_used',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='pipes_count_used',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='short_l_bands_count_used',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='structure_kit_used',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Fabrication', 'Fabrication')], default='Normal', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='t_bands_count_used',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='tags_count_used',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='tapes_black_count_used',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='installation',
            name='tapes_red_count_used',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
