# Generated by Django 5.2.10 on 2026-03-16 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0042_installation_ac_cable_black_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
