# Generated by Django 5.2.10 on 2026-03-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0043_enquiry_remarks_alter_enquiry_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pan_card',
            field=models.CharField(blank=True, help_text='PAN Card Number (10 Digits)', max_length=10, null=True),
        ),
    ]
