# Generated by Django 5.2.10 on 2026-03-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0044_userprofile_pan_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersurvey',
            name='workflow_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
