# Generated by Django 5.2.10 on 2026-04-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar_management', '0045_alter_customersurvey_workflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersurvey',
            name='property_tax_photo',
            field=models.FileField(blank=True, help_text='Photo/Scan of Property Tax', null=True, upload_to='surveys/documents/'),
        ),
        migrations.AlterField(
            model_name='surveymedia',
            name='media_type',
            field=models.CharField(choices=[('roof', 'Roof Photos'), ('pan_card', 'PAN Card'), ('aadhar', 'Aadhar Card'), ('current_bill', 'Current Bill'), ('bank_account', 'Bank Account'), ('parent_bank', 'Parent Bank'), ('property_tax', 'Property Tax')], max_length=50),
        ),
    ]
